---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: traefik-network-redirect@kubernetescrd,traefik-network-security@kubernetescrd
  name: my-app-ingress
  namespace: my-app

spec:
  rules:
    - host: "mydomain.com"
      http:
        paths:
          - backend:
              service:
                name: my-app-service
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: "test.mydomain.com"
      http:
        paths:
          - backend:
              service:
                name: my-app-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "*.mydomain.com"
      secretName: wildcard.mydomain.com-tls
    - hosts:
        - "test.mydomain.com"
        - "mydomain.com"
      secretName: mydomain.com-tls
